id = "ayla"
name = "Ayla"
version = "0.0.1"
schema_version = 1
authors = ["Ziad Skafi"]
description = "Language support for the Ayla programming language"
repository = "https://github.com/z-sk1/zed-ayla"

languages = ["languages/ayla"]
themes = []
icon_themes = []
capabilities = []

[grammars.ayla]
name = "ayla"
repository = "https://github.com/z-sk1/tree-sitter-ayla"
rev = "main"
