name = "Ayla"
grammar = "ayla"
scope = "source.ayla"
path_suffixes = ["ayla", "ayl"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false }
]
